### ISSUE TITLE
Feature request: support for multiple roles in the command

### ISSUE THREAD

**Issue by robvanmieghem** [Jumpscale/agentcontroller2#3]

**Comment by muhamadazmy** [comment]
I assume when multiple roles are provided the execution should be routed to agents that satisfies ALL given roles not ANY role. right ?

**Comment by robvanmieghem** [comment]
There are multiple use cases actually.
* Single role is specified:
  * Execute the command on ALL agents that satisfy
  * Execute the command on AN (1) agent that satisfies
* Multiple roles are specified:
  * Execute the command on ANY agent that matches 1 role
  * Execute the command on AN (1) agent that matches all roles
