### ISSUE TITLE
doc for python client advanced not good

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/agentcontroller2#4]
PLEASE DO NOT USE HTML SYNTAX INSIDE
see github/jumpscale/docs/MultiNode/AgentController2/Python Client.md

all needs to be in MD

**Comment by muhamadazmy** [comment]
The html doc is generated using 'Sphinx' tool. It doesn't support generating markdown syntax. Other tools that can be used to convert html to markdown doesn't generate pure markdown syntax (leaves lot of html) and ruins the formatting. 

I added a note in the doc that this is a generated documentation.

Should we remove this totally and add a link to the python file instead ?

**Comment by amrhassan** [comment]
I'm closing this on the count of the Python client not being in this repository any more.
